server.port=8082

customer.api.url=http://cds-customer-api:8080
product.catalog.url=http://cds-product-catalog:8081
payment.service.url=http://cds-payment-service:8083
notification.service.url=http://cds-notification-service:8084

order.timeout.ms=2000
order.max.retry=3
